# Generated by Django 3.0.8 on 2020-07-27 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200727_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='назва')),
                ('description', models.TextField(blank=True, verbose_name='опис')),
                ('logo', models.ImageField(upload_to='static/products/images', verbose_name='логотип')),
            ],
            options={
                'verbose_name': 'виробник',
                'verbose_name_plural': 'виробники',
            },
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='використовується'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductManufacturer'),
        ),
    ]
