# Generated by Django 3.0.8 on 2020-07-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200728_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='productmanufacturer',
            old_name='logo',
            new_name='logo_url',
        ),
    ]
