# Generated by Django 3.0.8 on 2020-08-01 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200728_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_active',
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_main_photo',
            field=models.CharField(choices=[('0', 'Додаткове'), ('1', 'Основне')], default=0, max_length=10, verbose_name='основне фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductManufacturer', verbose_name='виробник'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.ImageField(upload_to='static/products/product_images', verbose_name='посилання'),
        ),
        migrations.AlterField(
            model_name='productmanufacturer',
            name='logo_url',
            field=models.ImageField(upload_to='static/products/logo_images', verbose_name='завантажити'),
        ),
    ]
