# Generated by Django 3.1 on 2020-08-21 14:38

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200820_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(null=True, upload_to=products.models.product_main_image_uploader, verbose_name='посилання'),
        ),
        migrations.AlterField(
            model_name='productmanufacturer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/products/images/manufacturer_logo/', verbose_name='завантажити'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=60)),
                ('short_desc', models.CharField(blank=True, max_length=160)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Основна категорія')),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
