# Generated by Django 3.1 on 2020-08-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_category_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(null=True, upload_to='product_image_uploader', verbose_name='посилання'),
        ),
    ]
