# Generated by Django 3.1 on 2020-08-23 09:49

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200823_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide', models.ImageField(null=True, upload_to=products.models.product_slide_uploader, verbose_name='посилання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавлення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата оновлення')),
            ],
            options={
                'verbose_name': 'фотографія',
                'verbose_name_plural': 'фотографії',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.Category', verbose_name='категорія'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(null=True, upload_to=products.models.product_main_image_uploader, verbose_name='посилання'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productmanufacturer', verbose_name='виробник'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.AddField(
            model_name='productslide',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='products.product', verbose_name='товар'),
        ),
    ]
