# Generated by Django 3.1 on 2020-08-23 14:46

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20200823_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productslide',
            options={'ordering': ['created_at'], 'verbose_name': 'слайд', 'verbose_name_plural': 'слайд'},
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(null=True, upload_to=products.models.product_main_image_uploader, verbose_name='основне фото'),
        ),
    ]
