# Generated by Django 3.0.8 on 2020-08-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200801_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='is_main_photo',
            field=models.BooleanField(default=False, verbose_name='основне фото'),
        ),
    ]
