# Generated by Django 3.1 on 2020-08-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200812_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='productmanufacturer',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(null=True, upload_to='products/product_images', verbose_name='посилання'),
        ),
        migrations.AddField(
            model_name='productmanufacturer',
            name='logo',
            field=models.ImageField(null=True, upload_to='products/manufacturer_logo', verbose_name='завантажити'),
        ),
    ]
