# Generated by Django 3.1 on 2020-08-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200820_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=60, null=True, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(null=True, verbose_name='на складі'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(null=True, upload_to='products/images/product_images', verbose_name='посилання'),
        ),
        migrations.AlterField(
            model_name='productmanufacturer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/manufacturer_logo', verbose_name='завантажити'),
        ),
    ]
