# Generated by Django 3.1 on 2020-08-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200821_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категорія', 'verbose_name_plural': 'категорії'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=60, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='category',
            name='short_desc',
            field=models.CharField(blank=True, max_length=160, verbose_name='короткий опис'),
        ),
    ]
