# Generated by Django 3.1 on 2020-09-12 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20200823_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productslide',
            options={'ordering': ['created_at'], 'verbose_name': 'слайд', 'verbose_name_plural': 'слайди'},
        ),
    ]
