# Generated by Django 3.1 on 2020-09-12 18:57

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200820_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=13, null=True, region=None, verbose_name='номер телефону'),
        ),
    ]
