# Generated by Django 3.0.8 on 2020-08-08 11:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата заповнення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('NW', 'Новий'), ('PC', 'Комплектується'), ('TD', 'Переданий на доставку'), ('CP', 'Виконаний'), ('CN', 'Скасований'), ('RT', 'Повернення')], default='NW', max_length=2, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='order',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата оновлення'),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ціна за шт.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productinorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='кількість'),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ціна'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Customer', verbose_name='клієнт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='загальна вартість замовлення'),
        ),
    ]
