# Generated by Django 3.0.8 on 2020-08-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200808_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'клієнт', 'verbose_name_plural': 'клієнти'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'замовлення', 'verbose_name_plural': 'замовлення'},
        ),
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'товар в замовленні', 'verbose_name_plural': 'товари в замовленні'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='comment',
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=240, verbose_name='коментар'),
        ),
    ]
