# Generated by Django 3.0.8 on 2020-08-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200808_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ціна'),
        ),
    ]
