# Generated by Django 3.1 on 2020-09-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200913_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='NP_warehouses',
            field=models.CharField(max_length=100, null=True, verbose_name='нова пошта'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(max_length=30, null=True, verbose_name='місто'),
        ),
    ]
