# Generated by Django 3.1 on 2020-09-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200927_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='NP_warehouses',
        ),
        migrations.AddField(
            model_name='order',
            name='np_warehouses',
            field=models.CharField(max_length=100, null=True, verbose_name='адрес відділення'),
        ),
    ]
